1.21.11-4

diff --git a/.github/workflows/build-release.yml b/.github/workflows/build-release.yml
--- a/.github/workflows/build-release.yml
+++ b/.github/workflows/build-release.yml
@@ -1,135 +1,187 @@
-# Used when a release is pushed to GitHub
-# This does not make use of any caching as to ensure a clean build
-# https://github.com/CaffeineMC/sodium/blob/dc7dc4c634316ac8b510d2dc8290079ebc462778/.github/workflows/build-release.yml
-# https://github.com/klikli-dev/occultism/blob/4e98f6753d61403d5efcb87368d63bd7c793d2e5/.github/workflows/build_and_publish.yaml
-# https://github.com/Kira-NT/mc-publish
-# https://wiki.fabricmc.net/tutorial:publishing_mods_using_github_actions
-
-name: build-release
+name: "build-release"
 
 on:
   push:
     tags:
-      - 'alpha/v**'
-      - 'beta/v**'
-      - 'release/v**'
-  workflow_dispatch:
-    inputs:
-      tag:
-        description: 'Tag to build from'
-        required: true
+      - "alpha/v**"
+      - "beta/v**"
+      - "release/v**"
 
 jobs:
-  build:
-    runs-on: ubuntu-latest
+  release:
+    runs-on: "ubuntu-latest"
+
+    permissions:
+      contents: "write"
 
     steps:
-      - name: Checkout repository
-        uses: actions/checkout@v4
+      - name: "Checkout repository"
+        uses: "actions/checkout@v6"
         with:
           fetch-depth: 0
 
       - name: Setup JDK 17
-        uses: actions/setup-java@v4
+        uses: actions/setup-java@v5
         with:
-          java-version: '17'
-          distribution: 'temurin'
+          java-version: "17"
+          distribution: "temurin"
 
-      - name: Setup Pakku
-        run: curl -L -o pakku.jar https://github.com/juraj-hrivnak/Pakku/releases/download/v1.3.2/pakku.jar
-
-      - name: Export modpack
-        run: java -jar pakku.jar export
-
-      - name: Get release type from Tag
-        id: get_release_type
+      - name: "Setup pakku"
         run: |
-          TAG_REF="${GITHUB_REF#refs/tags/}"
-          RELEASE_TYPE=$(echo "$TAG_REF" | cut -d '/' -f 1)
-          echo "release_type=$RELEASE_TYPE" >> $GITHUB_OUTPUT
+          curl -sSL -o pakku.jar https://github.com/juraj-hrivnak/Pakku/releases/latest/download/pakku.jar
 
-      - name: Get mc version from tag
-        id: get_mc_version
+      - name: "Get modpack info"
+        id: "info"
+        shell: bash
         run: |
-          TAG_REF="${GITHUB_REF#refs/tags/}"
-          MC_VERSION=$(echo "$TAG_REF" | cut -d '/' -f 2 | cut -d '-' -f 1)
-          echo "mc_version=$MC_VERSION" >> $GITHUB_OUTPUT
+          chmod +x .github/scripts/get_modpack_info.sh
+          .github/scripts/get_modpack_info.sh
 
-      - name: Get version from tag
-        id: get_pack_version
+      # This makes sure that when there is a tag push, the version in pakku.json has been increased
+      - name: "Validate version bump on tag"
         run: |
-          TAG_REF="${GITHUB_REF#refs/tags/}"
-          PACK_VERSION=$(echo "$TAG_REF" | cut -d '/' -f 2 | cut -d '-' -f 2)
-          echo "pack_version=$PACK_VERSION" >> $GITHUB_OUTPUT
+          CUR_VER=${{ steps.info.outputs.modpack_version }}
+          PREV_VER=${{ steps.info.outputs.previous_modpack_version }}
+          if [ "$PREV_VER" != "none" ] && [ "$CUR_VER" == "$PREV_VER" ]; then
+            TAG_NAME=${GITHUB_REF#refs/tags/}
+            echo "::error::VERSION in pakku.json NOT UPDATED!"
+            echo "::error::Expected version bump in pakku.json but received $CUR_VER (same as in tag ${{ steps.info.outputs.previous_tag }})."
+            echo "::error::Deleting tag '$TAG_NAME' and failing build..."
 
-      - name: Build changelog
-        id: get_changelog
-        run: |
-          REPO="github.com/${{ github.repository }}"
-          CURRENT_TAG="${GITHUB_REF#refs/tags/}"
-          echo "Current tag: $CURRENT_TAG"
-
-          # Copy new lock file so that we can generate a changelog later
-          cp pakku-lock.json pakku-lock-new.json
-
-          # All tags in current branch, without the current one
-          TAG_LIST=$(git tag --merged HEAD --sort=-creatordate | grep -E '^alpha/v|^beta/v|^release/v' | grep -v "$CURRENT_TAG" || true)
-          echo "Tag list: $TAG_LIST"
-
-          LAST_TAG=$(echo "$TAG_LIST" | sed -n 1p)
-          echo "Last tag: $LAST_TAG"
-
-          if [ -z "$LAST_TAG" ]; then
-            echo "No previous tag found. This might be the first release."
-            # Create an empty dummy file so the diff command doesn't crash
-            echo "{}" > pakku-lock-old.json
-          else
-            echo "Found previous tag: $LAST_TAG"
-
-            # Checkout previous tag to get the old file
-            git checkout "$LAST_TAG"
-            cp pakku-lock.json pakku-lock-old.json
+            # Delete the tag from the remote
+            git push origin ":refs/tags/$TAG_NAME"
+            exit 1
           fi
 
-          # Execute Diff
-          echo "Generating diff between $LAST_TAG and $CURRENT_TAG"
-          java -jar pakku.jar diff --verbose pakku-lock-old.json pakku-lock-new.json --markdown changelog.md
+      - name: "Export modpack"
+        run: |
+          java -jar pakku.jar --debug export
 
-          # 6. Read changelog and store in GITHUB_OUTPUT
-          echo "changelog<<EOF" >> $GITHUB_OUTPUT
-          cat changelog.md >> $GITHUB_OUTPUT
-          echo "" >> $GITHUB_OUTPUT
-          echo "EOF" >> $GITHUB_OUTPUT
+      - name: "Rename serverpack artifacts"
+        run: mv "build/serverpack/*.zip" "build/serverpack/${{ steps.info.outputs.modpack_name }}-Server-${{ steps.info.outputs.modpack_version }}.zip"
 
-          echo "Release type is: ${{ steps.get_release_type.outputs.release_type }}"
-          echo "MC version is: ${{ steps.get_mc_version.outputs.mc_version }}"
-          echo "Pack version is: ${{ steps.get_pack_version.outputs.pack_version }}"
+      - name: "Upload serverpack artifacts to GitHub actions"
+        uses: "actions/upload-artifact@v6"
+        with:
+          name: "${{ steps.info.outputs.modpack_name }}-server-artifacts-${{ github.run_number }}"
+          path: "build/serverpack/*.zip"
 
-      - name: Upload to Modrinth & Curseforge
+      - name: "Unzip serverpack"
+        run: |
+          serverpack_zip=$(find build/serverpack -type f -name '*.zip' | head -n1)
+          unzip -q "$serverpack_zip" -d server-files
+          chmod -R 755 server-files
+
+      - name: "Start Server"
+        timeout-minutes: 15
+        run: |
+          docker run --name minecraft-server-test -d -it \
+            -v ${{ github.workspace }}/server-files:/data \
+            -e EULA=TRUE \
+            -e TYPE=${{ steps.info.outputs.modpack_loader }} \
+            -e VERSION=${{ steps.info.outputs.minecraft_version }} \
+            -e MEMORY=4G \
+            -e MAX_WORLD_SIZE=1 \
+            -e ONLINE_MODE=FALSE \
+            itzg/minecraft-server
+
+          # Realtime logs in GitHub actions
+          (docker logs -f minecraft-server-test || true) &
+
+          echo "Waiting for server to start..."
+          # Wait for container to be healthy
+          until [ "$(docker inspect -f '{{.State.Health.Status}}' minecraft-server-test)" == "healthy" ]; do
+              if [ "$(docker inspect -f '{{.State.Running}}' minecraft-server-test)" == "false" ]; then
+                  EXIT_CODE=$(docker inspect minecraft-server-test --format='{{.State.ExitCode}}')
+                  echo "::error::Server crashed with exit code $EXIT_CODE"
+                  docker logs minecraft-server-test
+                  exit 1
+              fi
+              sleep 5
+          done
+
+      - name: "Print crashes"
+        if: failure()
+        run: |
+          if [ -d "./server-files/crash-reports" ] && [ "$(ls -A ./server-files/crash-reports)" ]; then
+            cat ./server-files/crash-reports/*.txt
+          fi
+          if [ -f "./server-files/logs/latest.log" ]; then
+            tail -n 50 ./server-files/logs/latest.log
+          fi
+
+      - name: "Upload crash logs"
+        if: failure()
+        uses: "actions/upload-artifact@v6"
+        with:
+          name: "${{ steps.info.outputs.modpack_name }}-crash-logs-${{ github.run_number }}"
+          path: |
+            server-files/logs/
+            server-files/crash-reports/
+          retention-days: 7
+
+      - name: "Stop Server"
+        if: always()
+        run: |
+          docker stop minecraft-server-test || true
+          docker rm minecraft-server-test || true
+
+      - name: "Update Modchangelog file"
+        run: |
+          git config --global user.name "github-actions[bot]"
+          git config --global user.email "github-actions[bot]@users.noreply.github.com"
+          git add modchangelog.md
+
+          git commit -m "docs: update modchangelog for ${{ steps.info.outputs.modpack_version }} [skip ci]"
+
+          # We are on a tag so pushing needs to be done so we need to find out where to push to
+          TARGET_BRANCH=${{ steps.info.outputs.current_branch }}
+          git push origin HEAD:$TARGET_BRANCH
+
+      - name: "Upload to Modrinth"
+        if: ${{ vars.MR_PROJECT_ID != '' }}
         uses: Kir-Antipov/mc-publish@v3.3
         with:
-          modrinth-id: XPeeRdzS
-          modrinth-token: ${{ secrets.MODRINTH_API_TOKEN }}
+          modrinth-id: ${{ vars.MR_PROJECT_ID }}
+          modrinth-token: ${{ secrets.MR_PROJECT_API_TOKEN }}
 
-          curseforge-id: 563414
-          curseforge-token: ${{ secrets.CURSEFORGE_API_TOKEN }}
-
-          name: Wxrlds's Optimisations-${{ steps.get_mc_version.outputs.mc_version }}-${{ steps.get_pack_version.outputs.pack_version }}
+          name: ${{ steps.info.outputs.modpack_name }}-${{ steps.info.outputs.modpack_version }}
           game-versions: |
-            ${{ steps.get_mc_version.outputs.mc_version }}
+            ${{ steps.info.outputs.minecraft_version }}
           loaders: |
-            fabric
-          version-type: ${{ steps.get_release_type.outputs.release_type }}
-          version: ${{ steps.get_mc_version.outputs.mc_version }}-${{ steps.get_pack_version.outputs.pack_version }}
+            ${{ steps.info.outputs.modpack_loader }}
+          version-type: ${{ steps.info.outputs.modpack_release_type }}
+          version: ${{ steps.info.outputs.modpack_version }}
 
           changelog: |
-            ${{ steps.get_mc_version.outputs.mc_version }}-${{ steps.get_pack_version.outputs.pack_version }}
+            ${{ steps.info.outputs.modpack_version }}
 
             [Need a server? Just click on the Picture, use the code WXRLDS for 25% off of your first month and play with your friends!](https://bisecthosting.com/Wxrlds)
 
             [![Bisect Hosting](https://www.bisecthosting.com/partners/custom-banners/7ac5059a-f314-47ac-8598-45d00bd20eb4.png)](https://bisecthosting.com/Wxrlds)
 
-            ${{ steps.get_changelog.outputs.changelog }}
+            [Modchangelog](https://github.com/${{ github.repository }}/blob/${{ steps.info.outputs.current_branch }}/modchangelog.md#${{ steps.info.outputs.version_anchor }})
 
-          modrinth-files: build/modrinth/*.mrpack
-          curseforge-files: build/curseforge/*.zip
+      - name: "Upload to CurseForge"
+        if: ${{ vars.CF_PROJECT_ID != '' }}
+        uses: Kir-Antipov/mc-publish@v3.3
+        with:
+          modrinth-id: ${{ vars.CF_PROJECT_ID }}
+          modrinth-token: ${{ secrets.CF_PROJECT_API_TOKEN }}
+
+          name: ${{ steps.info.outputs.modpack_name }}-${{ steps.info.outputs.modpack_version }}
+          game-versions: |
+            ${{ steps.info.outputs.minecraft_version }}
+          loaders: |
+            ${{ steps.info.outputs.modpack_loader }}
+          version-type: ${{ steps.info.outputs.modpack_release_type }}
+          version: ${{ steps.info.outputs.modpack_version }}
+
+          changelog: |
+            ${{ steps.info.outputs.modpack_version }}
+
+            [Need a server? Just click on the Picture, use the code WXRLDS for 25% off of your first month and play with your friends!](https://bisecthosting.com/Wxrlds)
+
+            [![Bisect Hosting](https://www.bisecthosting.com/partners/custom-banners/7ac5059a-f314-47ac-8598-45d00bd20eb4.png)](https://bisecthosting.com/Wxrlds)
+
+            [Modchangelog](https://github.com/${{ github.repository }}/blob/${{ steps.info.outputs.current_branch }}/modchangelog.md#${{ steps.info.outputs.version_anchor }})
